[package]
name = "bls-multisig"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.4"
ff = "0.12.1"
sha2 = "0.9.9"
group = "0.12.1"
bls12_381 = { version = "0.7.0", features = ["experimental"] }
merlin = "3.0.0"

[[bin]]
name = "mskr"   
path = "src/bench.rs" 
